/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

dialect "mvel"

/**
 *
 * @author Pete
 */
import rulecalculator.TurningStepBean;
import rulecalculator.TurningStepBean.TurningType;
import rulecalculator.TurningStepBean.WorkpieceType;
import rulecalculator.TurningStepBean.InstrumentMaterial;
import javax.swing.JOptionPane;


rule "Diameter is too small" 
    when
        $step : TurningStepBean (diameter < 6, kind == TurningStepBean.ProcessKind.EXTERNAL_TURNING) or $step : TurningStepBean (diameter < 10, kind == TurningStepBean.ProcessKind.BORING)
    then
        $step.setIncorrect(true);
        $step.setErrorMessage("Диаметер слишком маленький");
end




rule "Set Kmv & Kmp for steel"
    lock-on-active true
    when
        step : TurningStepBean (workpieceMaterial == TurningStepBean.WorkpieceMaterial.STEEL)
    then
        modify(step){setKmv(1.25)};
        modify(step){setKmp(0.91)};
end

rule "Set Kmv & Kmp for cast iron"
    lock-on-active true
    when
        step : TurningStepBean (workpieceMaterial == TurningStepBean.WorkpieceMaterial.CAST_IRON)
    then
        modify(step){setKmv(1)};
        modify(step){setKmp(1)};
end

rule "Set Kpv for forging"
    lock-on-active true
    when
        step : TurningStepBean (workpieceType == TurningStepBean.WorkpieceType.FORGING)
    then
        step.kpv=0.8;
end

rule "Set Kpv for casting"
    lock-on-active true
    when
        step : TurningStepBean (workpieceType == TurningStepBean.WorkpieceType.CASTING)
    then
        modify(step){setKpv(0.85)};
end

rule "Set Kpv for rolling"
    lock-on-active true
    when
        step : TurningStepBean (workpieceType == TurningStepBean.WorkpieceType.ROLLING)
    then
        modify(step){setKpv(0.9)};
end

rule "Set Kpv for crustless"
    lock-on-active true
    when
        step : TurningStepBean (workpieceType == TurningStepBean.WorkpieceType.CRUSTLESS)
    then
        modify(step){setKpv(1)};
end

//rule "Set Kiv for crustless"
//    when
//        $step : TurningStepBean (workpieceMaterial == TurningStepBean.WorkpieceMaterial.STEEL, instrumentMaterial == TurningStepBean.InstrumentMaterial.T15K10)
//    then
//        $step.kpv=1;
//end

rule "Print" salience -100
    when
        step : TurningStepBean ()
    then
        System.out.println(step.toStr);
end